- name: Install ack-grep
  become: true
  package:
    name: ack-grep

- name: Add extensions to ack-grep types
  lineinfile:
    dest: ~/.ackrc
    create: yes
    state: present
    line: "{{ item }}"
  with_items:
  - "--type-set=rst:ext:rst"
  - "--type-set=robot:ext:robot"
  - "--type-set=txt:ext:txt"
  - "--type-set=ts:ext:ts"
  - "--type-set=yang:ext:yang"
  - "--type-set=js:ext:jsx,es,js"
  - "--type-set=jsx:ext:jsx,es,js"
  - "--type-set=es:ext:jsx,es,js"
  - "--type-set=md:ext:md,markdown"
  - "--type-set=markdown:ext:md,markdown"
  - "--type-set=py:ext:py"
