- name: Use vi mode for bash
  lineinfile:
    dest: ~/.bashrc
    state: present
    line: set -o vi

- name: Add bash aliases
  lineinfile:
    dest: ~/.bashrc
    state: present
    line: "{{ item }}"
  with_items:
  - "alias c='clear'"
  - "alias ta='tmux ls && tmux attach -d -t '"
