- name: Add docker bash aliases
  lineinfile:
    dest: ~/.bashrc
    state: present
    line: "alias {{ item }}"
  with_items:
  - dp='docker ps'
  - de='docker exec'
  - di='docker inspect'
  - dl='docker logs'
  - dr='docker run'
  - dst='docker stop'
  - drm='docker rm'
  - drmf='docker rm -f'
  - dclean='docker stop $(docker ps -q) && docker rm $(docker ps -a -q)'
