- name: Install misc utils 
  become: true
  package:
    name: "{{ item }}"
  with_items:
  - htop
  - tree
  - cmake

- include: ctags.yml
- include: ack-grep.yml
- include: elinks.yml
- include: tmux.yml
- include: bash.yml
- include: git.yml
- include: base16.yml
- include: docker.yml
- include: caps-lock-remap.yml
