- name: Install tmux 
  become: true
  package: name=tmux state=present

- name: Install xclip
  become: true
  package: name=xclip state=present

- name: Configure tmux
  copy: src=tmux.conf dest=~/.tmux.conf

- name: Tmux attach alias
  lineinfile: line="alias ta='tmux attach -d -t '" dest=~/.bashrc
