- name: Add sbt key
  become: true
  apt_key:
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present 

- name: Add repos
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
  - 'deb https://dl.bintray.com/sbt/debian /'
  - 'ppa:webupd8team/java'

- name: Accept Oracle license
  become: true
  debconf:
    name: "oracle-java8-installer"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: "select"

- name: Install packages
  become: true
  package:
    name: "{{ item }}"
    state: 'present'
    update_cache: 'yes'
  with_items:
  - oracle-java8-installer
  - sbt
