---
- name: Install utils 
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - ipython
  - python-virtualenv
  - htop
  - flake8
  - nodejs
  - npm

- name: Install utils 
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - ack-grep
  when: ansible_distribution == 'Ubuntu'

- name: Install jshint
  become: true
  npm:
    name: jshint
    global: yes

- name: Create nodejs alias
  become: true
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
