---
- name: Install utils 
  become: true
  package:
    name: "{{ item }}"
  with_items:
  - htop
  - nodejs
  - npm

- name: Install utils 
  become: true
  package:
    name: ack-grep
  when: ansible_distribution == 'Ubuntu'

- name: Add extensions to ack-grep types
  lineinfile:
    dest: ~/.ackrc
    create: yes
    state: present
    line: "{{ item }}"
  with_items:
  - "--type-set=rst:ext:rst"
  - "--type-set=robot:ext:robot"
  - "--type-set=txt:ext:txt"

- name: Install jshint
  become: true
  npm:
    name: jshint
    global: yes

- name: Create nodejs alias
  become: true
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
