- name: Install python utils
  become: true
  package:
    name: "{{ item }}"
  with_items:
  - ipython
  - ipython3
  - python-virtualenv
  - python-dev
  - python3-dev
  - pylint

- name: Add virtualenv bash alias
  lineinfile:
    dest: ~/.bashrc
    state: present
    line: alias vac='source ./venv/bin/activate'
