- name: Install xmonad
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - xmonad
  - xbacklight
  - suckless-tools

- name: Create xmonad dir
  file: path=~/.xmonad state=directory

- name: Configure xmonad
  copy: src=xmonad.hs dest=~/.xmonad/xmonad.hs
