---
- name: Install tmux 
  sudo: true
  apt: name=tmux state=present

- name: Configure tmux
  copy: src=tmux.conf dest=~/.tmux.conf

- name: Tmux alias
  lineinfile: line="alias tmux='tmux -2'" dest=~/.bashrc
