- name: Install dependencies
  become: true
  package: name=libncurses-dev
  when: ansible_distribution == 'Ubuntu'

- name: Install dependencies
  become: true
  package: name=ncurses-devel
  when: ansible_distribution == 'Fedora'

- name: Clone vim
  git: 
    repo: https://github.com/vim/vim
    dest: /tmp/vim
    depth: 1

- name: Compile vim
  command: |
    ./configure 
            --with-x
            --with-features=huge
            --enable-multibyte
            --enable-rubyinterp=yes
            --enable-pythoninterp=yes
            --enable-python3interp=yes
            --enable-perlinterp=yes
            --enable-luainterp=yes
            --prefix=/usr/local && make
  args:
    chdir: /tmp/vim

- name: Install vim
  become: true
  command: make install
  args:
    chdir: /tmp/vim

- stat: path=~/.vim
  register: vimhome

- name: Clone vim config
  git:
    repo: https://github.com/ealang/vimconf
    dest: ~/.vim
  when: vimhome.stat.exists == False
