- name: Install vim
  become: true
  package:
    name: vim-gtk3

- name: Allow Ctrl-S in terminal
  lineinfile: line="stty -ixon" dest=~/.bashrc

- name: Create vimundo dir
  file: path=~/.vimundo state=directory

- name: Write Intellij vimrc
  copy: src=ideavimrc dest=~/.ideavimrc

- name: Add bash alias
  lineinfile:
    dest: ~/.bashrc
    state: present
    line: alias v='vim'
