- stat: path=/usr/local/bin/vim
  register: vim

- include: install.yml
  when: vim.stat.exists == False

- name: Allow Ctrl-S in terminal
  lineinfile: line="stty -ixon" dest=~/.bashrc

- name: Bind caps -> esc
  lineinfile:
    dest: ~/.xsessionrc
    state: present
    create: yes
    line: "setxkbmap -option caps:escape"

- name: Create vimundo dir
  file: path=~/.vimundo state=directory

- name: Write Intellij vimrc
  copy: src=ideavimrc dest=~/.ideavimrc
