- name: Test for vim install
  command: "which vim"
  register: vim
  ignore_errors: yes

- include: install.yml
  when: vim.stdout == ""

- name: Allow Ctrl-S in terminal
  lineinfile: line="stty -ixon" dest=~/.bashrc

- name: Bind caps -> esc
  lineinfile:
    dest: ~/.xsessionrc
    state: present
    create: yes
    line: "setxkbmap -option caps:escape"

- name: Create vimundo dir
  file: path=~/.vimundo state=directory

- name: Write Intellij vimrc
  copy: src=ideavimrc dest=~/.ideavimrc
