- stat: path=/usr/local/bin/vim
  register: vim
  when: ansible_distribution == 'Ubuntu'

- stat: path=/usr/bin/vim
  register: vim
  when: ansible_distribution == 'Fedora'

- include: install.yml
  when: vim.stat.exists == False

- name: Allow Ctrl-S
  lineinfile: line="stty -ixon" dest=~/.bashrc

- name: Bind caps -> esc
  lineinfile:
    dest: ~/.xsessionrc
    state: present
    create: yes
    line: "setxkbmap -option caps:escape"
