---
- name: Install dependencies
  sudo: true
  apt: name=libncurses-dev

- name: Clone vim
  git: 
    repo: https://github.com/vim/vim
    dest: /tmp/vim
    depth: 1

- name: Compile vim
  command: make
  args:
    chdir: /tmp/vim

- name: Install vim
  sudo: true
  command: make install
  args:
    chdir: /tmp/vim

- name: Clone vim config
  git:
    repo: https://github.com/ealang/vimconf
    dest: ~/.vim

- name: Allow Ctrl-S
  lineinfile: line="stty -ixon" dest=~/.bashrc
