- name: Create xmonad dir
  file: path=~/.xmonad state=directory

- name: Configure xmonad
  copy: src=xmonad.hs dest=~/.xmonad/xmonad.hs

- name: Bind caps -> esc
  copy: src=xsessionrc dest=~/.xsessionrc
