- name: Install xmonad
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - xmonad

- name: Create xmonad dir
  file: path=~/.xmonad state=directory

- name: Configure xmonad
  copy: src=xmonad.hs dest=~/.xmonad/xmonad.hs
